### PR TITLE
Fix table row spacing in Chrome.

### PR DESCRIPTION
**Pull request by jenna-h**

### CODE REVIEW

**Comment by tabascq** [comment]
This will mess with the ability to style by changing cell width/height, and I'd like to avoid changing that if possible. What does this do, exactly?

**Comment by jenna-h** [comment]
Currently, the demos on your website look like this on Chrome on my machine (but they look fine on Firefox)!

image

Adding just one of the two (display: block, or height: 40px) doesn't work; it has to be both. Apparently this has to do with Chrome's default rendering of tables (maybe from a recent update?), and it's annoying to work around.

Re: setting height to 40, currently [we say that `.puzzle-entry td` has width and height 40px](https://github.com/tabascq/PuzzleJS/pull/28/files#diff-f450f965c0f766436285196aa69ef8517deb96bd7fdf7e0f30332890c694db95R35-R36). If you want, you can make a [CSS variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for example `.puzzle-entry { --grid-size: 40px; }` and then use the variable elsewhere. You can also change the variable value with JS if that's needed.

Could you give an example of where the tr height would not be equal to the td height?

**Comment by tabascq** [comment]
I like the CSS variable approach. TBH I've never seen a CSS variable defined anywhere other than `:root` or else I would have done this sooner as it's better for eventual hex grids.

That said, I don't want to make the change without updating the styling reference plus all demos that change cell sizes, including documenting the breaking change. I can get that done by the end of this weekend (if not today) if you'd like.

**Comment by jenna-h** [comment]
That would be great. Sorry, I wasn't aware of anywhere that cell sizes were
changed; I trust you to update the demos accordingly!

**Comment by tabascq** [comment]
Please check out PR #29; if that works for you, then I will merge that one and close this one.

**Comment by tabascq** [comment]
Closing in favor of #29.

**Pull request closed without merging**
